/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz_grafica;


/**
 *
 * @author Juan
 */
public class jframeprincipal extends javax.swing.JFrame {

    /**
     * Creates new form jframeprincipal
     */
    public jframeprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setActionCommand("pos1A");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 70, 80));

        jButton2.setActionCommand("pos1B");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 70, 80));

        jButton3.setActionCommand("pos1A");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 70, 80));

        jButton4.setActionCommand("pos1B");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 70, 80));

        jButton5.setActionCommand("pos1A");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 70, 80));

        jButton6.setActionCommand("pos1B");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 70, 80));

        jButton7.setActionCommand("pos1A");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 70, 80));

        jButton8.setActionCommand("pos1B");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 70, 80));

        jButton9.setActionCommand("pos1A");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 70, 70));

        jButton10.setActionCommand("pos1B");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 70, 70));

        jButton11.setActionCommand("pos1A");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 70, 70));

        jButton12.setActionCommand("pos1B");
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 70, 70));

        jButton13.setActionCommand("pos1A");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 70, 70));

        jButton14.setActionCommand("pos1B");
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 70, 70));

        jButton15.setActionCommand("pos1A");
        jButton15.setBorder(null);
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 70, 70));

        jButton16.setActionCommand("pos1B");
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 70, 70));

        jButton17.setActionCommand("pos1A");
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 70, 70));

        jButton18.setActionCommand("pos1B");
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 70, 70));

        jButton19.setActionCommand("pos1A");
        jButton19.setBorder(null);
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 70, 70));

        jButton20.setActionCommand("pos1B");
        jButton20.setBorder(null);
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 70, 70));

        jButton21.setActionCommand("pos1A");
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 70, 70));

        jButton22.setActionCommand("pos1B");
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 70, 70));

        jButton23.setActionCommand("pos1A");
        jButton23.setBorder(null);
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 70, 70));

        jButton24.setActionCommand("pos1B");
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 70, 70));

        jButton25.setActionCommand("pos1A");
        jButton25.setBorder(null);
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 70, 70));

        jButton26.setActionCommand("pos1B");
        jButton26.setBorder(null);
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 70, 70));

        jButton27.setActionCommand("pos1A");
        jButton27.setBorder(null);
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 70, 70));

        jButton28.setActionCommand("pos1B");
        jButton28.setBorder(null);
        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 70, 70));

        jButton29.setActionCommand("pos1A");
        jButton29.setBorder(null);
        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 70, 70));

        jButton30.setActionCommand("pos1B");
        jButton30.setBorder(null);
        jButton30.setBorderPainted(false);
        jButton30.setContentAreaFilled(false);
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 70, 70));

        jButton31.setActionCommand("pos1A");
        jButton31.setBorder(null);
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 70, 70));

        jButton32.setActionCommand("pos1B");
        jButton32.setBorder(null);
        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 70, 70));

        jButton33.setActionCommand("pos1A");
        jButton33.setBorder(null);
        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 70, 70));

        jButton34.setActionCommand("pos1B");
        jButton34.setBorder(null);
        jButton34.setBorderPainted(false);
        jButton34.setContentAreaFilled(false);
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, 70));

        jButton35.setActionCommand("pos1A");
        jButton35.setBorder(null);
        jButton35.setBorderPainted(false);
        jButton35.setContentAreaFilled(false);
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 70, 70));

        jButton36.setActionCommand("pos1B");
        jButton36.setBorder(null);
        jButton36.setBorderPainted(false);
        jButton36.setContentAreaFilled(false);
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 70, 70));

        jButton37.setActionCommand("pos1A");
        jButton37.setBorder(null);
        jButton37.setBorderPainted(false);
        jButton37.setContentAreaFilled(false);
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 70, 70));

        jButton38.setActionCommand("pos1B");
        jButton38.setBorder(null);
        jButton38.setBorderPainted(false);
        jButton38.setContentAreaFilled(false);
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 70, 70));

        jButton39.setActionCommand("pos1A");
        jButton39.setBorder(null);
        jButton39.setBorderPainted(false);
        jButton39.setContentAreaFilled(false);
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 70, 70));

        jButton40.setActionCommand("pos1B");
        jButton40.setBorder(null);
        jButton40.setBorderPainted(false);
        jButton40.setContentAreaFilled(false);
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 70, 70));

        jButton41.setActionCommand("pos1A");
        jButton41.setBorder(null);
        jButton41.setBorderPainted(false);
        jButton41.setContentAreaFilled(false);
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 70, 70));

        jButton42.setActionCommand("pos1B");
        jButton42.setBorder(null);
        jButton42.setBorderPainted(false);
        jButton42.setContentAreaFilled(false);
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 70, 70));

        jButton43.setActionCommand("pos1A");
        jButton43.setBorder(null);
        jButton43.setBorderPainted(false);
        jButton43.setContentAreaFilled(false);
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 70, 70));

        jButton44.setActionCommand("pos1B");
        jButton44.setBorder(null);
        jButton44.setBorderPainted(false);
        jButton44.setContentAreaFilled(false);
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, 70));

        jButton45.setActionCommand("pos1A");
        jButton45.setBorder(null);
        jButton45.setBorderPainted(false);
        jButton45.setContentAreaFilled(false);
        getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 70, 70));

        jButton46.setActionCommand("pos1B");
        jButton46.setBorder(null);
        jButton46.setBorderPainted(false);
        jButton46.setContentAreaFilled(false);
        getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 70, 70));

        jButton47.setActionCommand("pos1B");
        jButton47.setBorder(null);
        jButton47.setBorderPainted(false);
        jButton47.setContentAreaFilled(false);
        getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 70, 70));

        jButton48.setActionCommand("pos1A");
        jButton48.setBorder(null);
        jButton48.setBorderPainted(false);
        jButton48.setContentAreaFilled(false);
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 70, 70));

        jButton49.setActionCommand("pos1A");
        jButton49.setBorder(null);
        jButton49.setBorderPainted(false);
        jButton49.setContentAreaFilled(false);
        getContentPane().add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 70, 70));

        jButton50.setActionCommand("pos1B");
        jButton50.setBorder(null);
        jButton50.setBorderPainted(false);
        jButton50.setContentAreaFilled(false);
        getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 70, 70));

        jButton51.setActionCommand("pos1B");
        jButton51.setBorder(null);
        jButton51.setBorderPainted(false);
        jButton51.setContentAreaFilled(false);
        getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 70, 70));

        jButton52.setActionCommand("pos1A");
        jButton52.setBorder(null);
        jButton52.setBorderPainted(false);
        jButton52.setContentAreaFilled(false);
        getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 70, 70));

        jButton53.setActionCommand("pos1A");
        jButton53.setBorder(null);
        jButton53.setBorderPainted(false);
        jButton53.setContentAreaFilled(false);
        getContentPane().add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 70, 70));

        jButton54.setActionCommand("pos1B");
        jButton54.setBorder(null);
        jButton54.setBorderPainted(false);
        jButton54.setContentAreaFilled(false);
        getContentPane().add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 70, 70));

        jButton55.setActionCommand("pos1B");
        jButton55.setBorder(null);
        jButton55.setBorderPainted(false);
        jButton55.setContentAreaFilled(false);
        getContentPane().add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 70, 70));

        jButton56.setActionCommand("pos1A");
        jButton56.setBorder(null);
        jButton56.setBorderPainted(false);
        jButton56.setContentAreaFilled(false);
        getContentPane().add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 70, 70));

        jButton57.setActionCommand("pos1A");
        jButton57.setBorder(null);
        jButton57.setBorderPainted(false);
        jButton57.setContentAreaFilled(false);
        getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 70, 70));

        jButton58.setActionCommand("pos1B");
        jButton58.setBorder(null);
        jButton58.setBorderPainted(false);
        jButton58.setContentAreaFilled(false);
        getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, 70));

        jButton59.setActionCommand("pos1B");
        jButton59.setBorder(null);
        jButton59.setBorderPainted(false);
        jButton59.setContentAreaFilled(false);
        getContentPane().add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 70));

        jButton60.setActionCommand("pos1A");
        jButton60.setBorder(null);
        jButton60.setBorderPainted(false);
        jButton60.setContentAreaFilled(false);
        getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 70, 70));

        jButton61.setActionCommand("pos1A");
        jButton61.setBorder(null);
        jButton61.setBorderPainted(false);
        jButton61.setContentAreaFilled(false);
        getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 70, 70));

        jButton62.setActionCommand("pos1B");
        jButton62.setBorder(null);
        jButton62.setBorderPainted(false);
        jButton62.setContentAreaFilled(false);
        getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 70, 70));

        jButton63.setActionCommand("pos1B");
        jButton63.setBorder(null);
        jButton63.setBorderPainted(false);
        jButton63.setContentAreaFilled(false);
        getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 70, 70));

        jButton64.setActionCommand("pos1A");
        jButton64.setBorder(null);
        jButton64.setBorderPainted(false);
        jButton64.setContentAreaFilled(false);
        getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 70, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_grafica/tablero_final.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
