/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p_final.interfaz_grafica;
import p_final.*;
import java.util.*;
import javax.swing.*;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.util.ArrayList;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Juan
 */
public class jframeprincipal extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form jframeprincipal
     */
    public jframeprincipal() {
        initComponents();
        try{
        sys.añadir10Problemas();}
        catch(FileNotFoundException e1){}
        catch(IOException e2){}
        catch (p_final.IllegalFormatException e3){}         
        catch(IllegalTableroException e4){}
        catch(IllegalSolutionException e5){}
        catch(IllegalMovementException e6){}
        catch(IllegalFileExtension e7){}
        deshabilitarUI();
        cargarListaBotones();
        desactivarBotones();
        for(JButton btn: listaBotones){
            btn.addActionListener(new ManejadorDeBotones(btn, this));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn8a = new javax.swing.JButton();
        btn8b = new javax.swing.JButton();
        btn8c = new javax.swing.JButton();
        btn8d = new javax.swing.JButton();
        btn8e = new javax.swing.JButton();
        btn8f = new javax.swing.JButton();
        btn8g = new javax.swing.JButton();
        btn8h = new javax.swing.JButton();
        btn7a = new javax.swing.JButton();
        btn7b = new javax.swing.JButton();
        btn7c = new javax.swing.JButton();
        btn7d = new javax.swing.JButton();
        btn7e = new javax.swing.JButton();
        btn7f = new javax.swing.JButton();
        btn7g = new javax.swing.JButton();
        btn7h = new javax.swing.JButton();
        btn6a = new javax.swing.JButton();
        btn6b = new javax.swing.JButton();
        btn6c = new javax.swing.JButton();
        btn6d = new javax.swing.JButton();
        btn6e = new javax.swing.JButton();
        btn6f = new javax.swing.JButton();
        btn6g = new javax.swing.JButton();
        btn6h = new javax.swing.JButton();
        btn5a = new javax.swing.JButton();
        btn5b = new javax.swing.JButton();
        btn5c = new javax.swing.JButton();
        btn5d = new javax.swing.JButton();
        btn5e = new javax.swing.JButton();
        btn5f = new javax.swing.JButton();
        btn5g = new javax.swing.JButton();
        btn5h = new javax.swing.JButton();
        btn4a = new javax.swing.JButton();
        btn4b = new javax.swing.JButton();
        btn4c = new javax.swing.JButton();
        btn4d = new javax.swing.JButton();
        btn4e = new javax.swing.JButton();
        btn4f = new javax.swing.JButton();
        btn4g = new javax.swing.JButton();
        btn4h = new javax.swing.JButton();
        btn3a = new javax.swing.JButton();
        btn3b = new javax.swing.JButton();
        btn3c = new javax.swing.JButton();
        btn3d = new javax.swing.JButton();
        btn3e = new javax.swing.JButton();
        btn3f = new javax.swing.JButton();
        btn3g = new javax.swing.JButton();
        btn3h = new javax.swing.JButton();
        btn2a = new javax.swing.JButton();
        btn2b = new javax.swing.JButton();
        btn2c = new javax.swing.JButton();
        btn2d = new javax.swing.JButton();
        btn2e = new javax.swing.JButton();
        btn2f = new javax.swing.JButton();
        btn2g = new javax.swing.JButton();
        btn2h = new javax.swing.JButton();
        btn1a = new javax.swing.JButton();
        btn1b = new javax.swing.JButton();
        btn1c = new javax.swing.JButton();
        btn1d = new javax.swing.JButton();
        btn1e = new javax.swing.JButton();
        btn1f = new javax.swing.JButton();
        btn1g = new javax.swing.JButton();
        btn1h = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextPassword = new javax.swing.JPasswordField();
        jLabelInsertarNombre = new javax.swing.JLabel();
        jLabelInsertarPass = new javax.swing.JLabel();
        jLabelInformacion = new javax.swing.JLabel();
        jButtonNombrePassword = new javax.swing.JButton();
        jButtonSubirProblema = new javax.swing.JButton();
        jButtonResolverProblema = new javax.swing.JButton();
        jButtonEstadisticasPersonales = new javax.swing.JButton();
        jButtonEstadisticasProblemas = new javax.swing.JButton();
        jButtonVerClasificacion = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn8a.setBorderPainted(false);
        btn8a.setContentAreaFilled(false);
        btn8a.setName("8a"); // NOI18N
        getContentPane().add(btn8a, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 80));

        btn8b.setBorderPainted(false);
        btn8b.setContentAreaFilled(false);
        btn8b.setName("8b"); // NOI18N
        getContentPane().add(btn8b, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 80, 80));

        btn8c.setBorderPainted(false);
        btn8c.setContentAreaFilled(false);
        btn8c.setName("8c"); // NOI18N
        getContentPane().add(btn8c, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, 70));

        btn8d.setBorderPainted(false);
        btn8d.setContentAreaFilled(false);
        btn8d.setName("8d"); // NOI18N
        getContentPane().add(btn8d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 70, 70));

        btn8e.setBorderPainted(false);
        btn8e.setContentAreaFilled(false);
        btn8e.setName("8e"); // NOI18N
        getContentPane().add(btn8e, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 70, 60));

        btn8f.setBorderPainted(false);
        btn8f.setContentAreaFilled(false);
        btn8f.setName("8f"); // NOI18N
        getContentPane().add(btn8f, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 70, 60));

        btn8g.setBorderPainted(false);
        btn8g.setContentAreaFilled(false);
        btn8g.setName("8g"); // NOI18N
        getContentPane().add(btn8g, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 70, 60));

        btn8h.setBorderPainted(false);
        btn8h.setContentAreaFilled(false);
        btn8h.setName("8h"); // NOI18N
        getContentPane().add(btn8h, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 70, 60));

        btn7a.setBorderPainted(false);
        btn7a.setContentAreaFilled(false);
        btn7a.setName("7a"); // NOI18N
        getContentPane().add(btn7a, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 70, 70));

        btn7b.setBorderPainted(false);
        btn7b.setContentAreaFilled(false);
        btn7b.setName("7b"); // NOI18N
        getContentPane().add(btn7b, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 70, 70));

        btn7c.setBorderPainted(false);
        btn7c.setContentAreaFilled(false);
        btn7c.setName("7c"); // NOI18N
        getContentPane().add(btn7c, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 70, 70));

        btn7d.setBorderPainted(false);
        btn7d.setContentAreaFilled(false);
        btn7d.setName("7d"); // NOI18N
        getContentPane().add(btn7d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 70, 70));

        btn7e.setBorderPainted(false);
        btn7e.setContentAreaFilled(false);
        btn7e.setName("7e"); // NOI18N
        getContentPane().add(btn7e, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 70, 70));

        btn7f.setBorderPainted(false);
        btn7f.setContentAreaFilled(false);
        btn7f.setName("7f"); // NOI18N
        getContentPane().add(btn7f, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 70, 70));

        btn7g.setBorderPainted(false);
        btn7g.setContentAreaFilled(false);
        btn7g.setName("7g"); // NOI18N
        getContentPane().add(btn7g, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 70, 70));

        btn7h.setBorderPainted(false);
        btn7h.setContentAreaFilled(false);
        btn7h.setName("7h"); // NOI18N
        getContentPane().add(btn7h, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 70, 70));

        btn6a.setBorderPainted(false);
        btn6a.setContentAreaFilled(false);
        btn6a.setName("6a"); // NOI18N
        getContentPane().add(btn6a, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 70, 70));

        btn6b.setBorderPainted(false);
        btn6b.setContentAreaFilled(false);
        btn6b.setName("6b"); // NOI18N
        getContentPane().add(btn6b, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 70, 70));

        btn6c.setBorderPainted(false);
        btn6c.setContentAreaFilled(false);
        btn6c.setName("6c"); // NOI18N
        getContentPane().add(btn6c, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, 70));

        btn6d.setBorderPainted(false);
        btn6d.setContentAreaFilled(false);
        btn6d.setName("6d"); // NOI18N
        getContentPane().add(btn6d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 70, 70));

        btn6e.setBorderPainted(false);
        btn6e.setContentAreaFilled(false);
        btn6e.setName("6e"); // NOI18N
        getContentPane().add(btn6e, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 70, 70));

        btn6f.setBorderPainted(false);
        btn6f.setContentAreaFilled(false);
        btn6f.setName("6f"); // NOI18N
        getContentPane().add(btn6f, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 70, 70));

        btn6g.setBorderPainted(false);
        btn6g.setContentAreaFilled(false);
        btn6g.setName("6g"); // NOI18N
        getContentPane().add(btn6g, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 70, 70));

        btn6h.setBorderPainted(false);
        btn6h.setContentAreaFilled(false);
        btn6h.setName("6h"); // NOI18N
        getContentPane().add(btn6h, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 70, 70));

        btn5a.setBorderPainted(false);
        btn5a.setContentAreaFilled(false);
        btn5a.setName("5a"); // NOI18N
        getContentPane().add(btn5a, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, 70));

        btn5b.setBorderPainted(false);
        btn5b.setContentAreaFilled(false);
        btn5b.setName("5b"); // NOI18N
        getContentPane().add(btn5b, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 70, 70));

        btn5c.setBorderPainted(false);
        btn5c.setContentAreaFilled(false);
        btn5c.setName("5c"); // NOI18N
        getContentPane().add(btn5c, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 70, 70));

        btn5d.setBorderPainted(false);
        btn5d.setContentAreaFilled(false);
        btn5d.setName("5d"); // NOI18N
        getContentPane().add(btn5d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 70, 70));

        btn5e.setBorderPainted(false);
        btn5e.setContentAreaFilled(false);
        btn5e.setName("5e"); // NOI18N
        getContentPane().add(btn5e, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 70, 70));

        btn5f.setBorderPainted(false);
        btn5f.setContentAreaFilled(false);
        btn5f.setName("5f"); // NOI18N
        getContentPane().add(btn5f, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 70, 70));

        btn5g.setBorderPainted(false);
        btn5g.setContentAreaFilled(false);
        btn5g.setName("5g"); // NOI18N
        getContentPane().add(btn5g, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 70, 70));

        btn5h.setBorderPainted(false);
        btn5h.setContentAreaFilled(false);
        btn5h.setName("5h"); // NOI18N
        getContentPane().add(btn5h, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 70, 70));

        btn4a.setBorderPainted(false);
        btn4a.setContentAreaFilled(false);
        btn4a.setName("4a"); // NOI18N
        getContentPane().add(btn4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 70, 70));

        btn4b.setBorderPainted(false);
        btn4b.setContentAreaFilled(false);
        btn4b.setName("4b"); // NOI18N
        getContentPane().add(btn4b, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 70, 70));

        btn4c.setBorderPainted(false);
        btn4c.setContentAreaFilled(false);
        btn4c.setName("4c"); // NOI18N
        getContentPane().add(btn4c, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 70, 70));

        btn4d.setBorderPainted(false);
        btn4d.setContentAreaFilled(false);
        btn4d.setName("4d"); // NOI18N
        getContentPane().add(btn4d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 70, 70));

        btn4e.setBorderPainted(false);
        btn4e.setContentAreaFilled(false);
        btn4e.setName("4e"); // NOI18N
        getContentPane().add(btn4e, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 70, 70));

        btn4f.setBorderPainted(false);
        btn4f.setContentAreaFilled(false);
        btn4f.setName("4f"); // NOI18N
        getContentPane().add(btn4f, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 70, 70));

        btn4g.setBorderPainted(false);
        btn4g.setContentAreaFilled(false);
        btn4g.setName("4g"); // NOI18N
        getContentPane().add(btn4g, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 70, 70));

        btn4h.setBorderPainted(false);
        btn4h.setContentAreaFilled(false);
        btn4h.setName("4h"); // NOI18N
        getContentPane().add(btn4h, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 70, 70));

        btn3a.setBorderPainted(false);
        btn3a.setContentAreaFilled(false);
        btn3a.setName("3a"); // NOI18N
        getContentPane().add(btn3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 70, 70));

        btn3b.setBorderPainted(false);
        btn3b.setContentAreaFilled(false);
        btn3b.setName("3b"); // NOI18N
        getContentPane().add(btn3b, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 70, 70));

        btn3c.setBorderPainted(false);
        btn3c.setContentAreaFilled(false);
        btn3c.setName("3c"); // NOI18N
        getContentPane().add(btn3c, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 70, 70));

        btn3d.setBorderPainted(false);
        btn3d.setContentAreaFilled(false);
        btn3d.setName("3d"); // NOI18N
        getContentPane().add(btn3d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 70, 70));

        btn3e.setBorderPainted(false);
        btn3e.setContentAreaFilled(false);
        btn3e.setName("3e"); // NOI18N
        getContentPane().add(btn3e, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 70, 70));

        btn3f.setBorderPainted(false);
        btn3f.setContentAreaFilled(false);
        btn3f.setName("3f"); // NOI18N
        getContentPane().add(btn3f, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 70, 70));

        btn3g.setBorderPainted(false);
        btn3g.setContentAreaFilled(false);
        btn3g.setName("3g"); // NOI18N
        getContentPane().add(btn3g, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 70, 70));

        btn3h.setBorderPainted(false);
        btn3h.setContentAreaFilled(false);
        btn3h.setName("3h"); // NOI18N
        getContentPane().add(btn3h, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 70, 70));

        btn2a.setBorderPainted(false);
        btn2a.setContentAreaFilled(false);
        btn2a.setName("2a"); // NOI18N
        getContentPane().add(btn2a, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 70, 70));

        btn2b.setBorderPainted(false);
        btn2b.setContentAreaFilled(false);
        btn2b.setName("2b"); // NOI18N
        getContentPane().add(btn2b, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 70, 70));

        btn2c.setBorderPainted(false);
        btn2c.setContentAreaFilled(false);
        btn2c.setName("2c"); // NOI18N
        getContentPane().add(btn2c, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 70, 70));

        btn2d.setBorderPainted(false);
        btn2d.setContentAreaFilled(false);
        btn2d.setName("2d"); // NOI18N
        getContentPane().add(btn2d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 70, 70));

        btn2e.setBorderPainted(false);
        btn2e.setContentAreaFilled(false);
        btn2e.setName("2e"); // NOI18N
        getContentPane().add(btn2e, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 70, 70));

        btn2f.setBorderPainted(false);
        btn2f.setContentAreaFilled(false);
        btn2f.setName("2f"); // NOI18N
        getContentPane().add(btn2f, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 70, 70));

        btn2g.setBorderPainted(false);
        btn2g.setContentAreaFilled(false);
        btn2g.setName("2g"); // NOI18N
        getContentPane().add(btn2g, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 70, 70));

        btn2h.setBorderPainted(false);
        btn2h.setContentAreaFilled(false);
        btn2h.setName("2h"); // NOI18N
        getContentPane().add(btn2h, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 70, 70));

        btn1a.setBorderPainted(false);
        btn1a.setContentAreaFilled(false);
        btn1a.setName("1a"); // NOI18N
        getContentPane().add(btn1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 70, 70));

        btn1b.setBorderPainted(false);
        btn1b.setContentAreaFilled(false);
        btn1b.setName("1b"); // NOI18N
        getContentPane().add(btn1b, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 70, 70));

        btn1c.setBorderPainted(false);
        btn1c.setContentAreaFilled(false);
        btn1c.setName("1c"); // NOI18N
        getContentPane().add(btn1c, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 70, 70));

        btn1d.setBorderPainted(false);
        btn1d.setContentAreaFilled(false);
        btn1d.setName("1d"); // NOI18N
        getContentPane().add(btn1d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 70, 70));

        btn1e.setBorderPainted(false);
        btn1e.setContentAreaFilled(false);
        btn1e.setName("1e"); // NOI18N
        getContentPane().add(btn1e, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 70, 70));

        btn1f.setBorderPainted(false);
        btn1f.setContentAreaFilled(false);
        btn1f.setName("1f"); // NOI18N
        getContentPane().add(btn1f, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 70, 70));

        btn1g.setBorderPainted(false);
        btn1g.setContentAreaFilled(false);
        btn1g.setName("1g"); // NOI18N
        getContentPane().add(btn1g, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 70, 70));

        btn1h.setBorderPainted(false);
        btn1h.setContentAreaFilled(false);
        btn1h.setName("1h"); // NOI18N
        getContentPane().add(btn1h, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 70, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p_final/interfaz_grafica/tablero_final.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jTextNombre.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 110, -1));

        jTextPassword.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        getContentPane().add(jTextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 120, -1));

        jLabelInsertarNombre.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabelInsertarNombre.setText("Inserta tu nombre");
        getContentPane().add(jLabelInsertarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jLabelInsertarPass.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabelInsertarPass.setText("Inserta tu contraseña");
        getContentPane().add(jLabelInsertarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jLabelInformacion.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        getContentPane().add(jLabelInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 790, 780, 50));

        jButtonNombrePassword.setText("OK");
        jButtonNombrePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNombrePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNombrePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, -1, -1));

        jButtonSubirProblema.setText("Subir problema");
        jButtonSubirProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubirProblemaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSubirProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 260, 20));

        jButtonResolverProblema.setText("Resolver problema");
        jButtonResolverProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResolverProblemaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResolverProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 35, 260, 20));

        jButtonEstadisticasPersonales.setText("Estadísticas personales");
        getContentPane().add(jButtonEstadisticasPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 260, 20));

        jButtonEstadisticasProblemas.setText("Estadísticas de los problemas");
        getContentPane().add(jButtonEstadisticasProblemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 260, 20));

        jButtonVerClasificacion.setText("Ver clasificación");
        getContentPane().add(jButtonVerClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 260, 20));

        jButton41.setText("Guardar o leer datos de la partida");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 790, 280, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Sistema sys = new Sistema();
    String nombre, pass;
    Usuario user;
    ArrayList<ModeloUsuario> AUSER;
    ArrayList<JButton> listaBotones;
    Pieza piezaSeleccionada;
    Tablero T;
    ManejadorDeBotones botonero;
    
    public Tablero getTablero(){
        return T;
    }
    
    
    final JFileChooser selectorArchivos = new JFileChooser(); //Creamos un selector de archivos
    private void habilitarUI(){
        jButtonNombrePassword.setVisible(false);//Esconder botón "OK"
        jTextNombre.setVisible(false);//Esconder cuadro de texto para leer nombre
        jTextPassword.setVisible(false);//Esconder cuadro de texto para leer password
        jLabelInsertarNombre.setVisible(false);//Esconder etiqueta de insertar nombre
        jLabelInsertarPass.setVisible(false);//Esconder etiqueta de insertar password
        jLabelInformacion.setText("Bienvenido, "+ nombre + ", disfruta de esta partida.");/*Sacar
        mensaje por nuestra terminal de información*/
        jButtonSubirProblema.setVisible(true);/*Posibilitamos subir problema ahora
        que tenemos un usuario que ha hecho log-in*/
        jButtonResolverProblema.setVisible(true);
        jButtonEstadisticasPersonales.setVisible(true);
        jButtonVerClasificacion.setVisible(true);
        jButtonEstadisticasProblemas.setVisible(true);
    }
    
    private void deshabilitarUI(){
        jButtonSubirProblema.setVisible(false);/*Posibilitamos subir problema ahora
        que tenemos un usuario que ha hecho log-in*/
        jButtonResolverProblema.setVisible(false);
        jButtonEstadisticasPersonales.setVisible(false);
        jButtonVerClasificacion.setVisible(false);
        jButtonEstadisticasProblemas.setVisible(false);
    }
    
    
    
    private void jButtonNombrePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNombrePasswordActionPerformed
        nombre = jTextNombre.getText();
        pass = jTextPassword.getText();
        int respuesta = 0;
        if(!nombre.equalsIgnoreCase("") && !pass.equalsIgnoreCase("")){
            if(sys.buscarUsuario(nombre, pass) == null){
                
                Object[] options = { "Sí", "No" };
                respuesta = JOptionPane.showOptionDialog(
                        this, //Ventana padre
                        "Usuario no encontrado. ¿Desea registrarse al sistema?",//Mensaje del cuerpo
                        "Atención",//Texto de encabezado
                        JOptionPane.YES_NO_OPTION, //Tipo de opciones a mostrar
                        JOptionPane.QUESTION_MESSAGE, //Tipo del mensaje a mostrar
                        null,//Icono a mostrar
                        options,//array con las elecciones posibles
                        options[0]);
            }else{
                user = sys.buscarUsuario(nombre, pass);
                habilitarUI();
            }
            if(respuesta==0){
                sys.registrarUsuario(nombre, pass);
                habilitarUI();
                user = sys.buscarUsuario(nombre, pass);
            }
        }
    }//GEN-LAST:event_jButtonNombrePasswordActionPerformed

    private void sacarError(String codigoError){
        JOptionPane.showMessageDialog(this, //ventana padre
                    codigoError, //objeto a mostrar
                    "Error", //
                    JOptionPane.ERROR_MESSAGE);
    }
    
    private void jButtonSubirProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubirProblemaActionPerformed
        int returnVal = selectorArchivos.showOpenDialog(this);/*Mostrar el explorador
        de archivos*/
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            /*Obtener el archivo seleccionado*/
            File archivo = selectorArchivos.getSelectedFile();
            String codigoError = "";
            try {
                /*Obtener la ruta del archivo seleccionado*/
                jLabelInformacion.setText(archivo.getCanonicalPath());
                user.leerEjemplo(jLabelInformacion.getText());
                pintarTablero();
            } catch (FileNotFoundException ex) {
                sacarError(ex.getMessage());
            } catch (p_final.IllegalFormatException | IllegalTableroException| 
                    IllegalSolutionException | IllegalMovementException | 
                    IllegalFileExtension | IOException ex) {
                sacarError(ex.getMessage());
            } 
            
            jLabelInformacion.setText(codigoError);
            sys.actualizarSistemaModelos();
    }//GEN-LAST:event_jButtonSubirProblemaActionPerformed
    }
    
    private void cargarListaBotones(){
        listaBotones = new ArrayList<>();
        listaBotones.add(0,btn8a);
        listaBotones.add(1,btn8b);
        listaBotones.add(2,btn8c);
        listaBotones.add(3,btn8d);
        listaBotones.add(4,btn8e);
        listaBotones.add(5,btn8f);
        listaBotones.add(6,btn8g);
        listaBotones.add(7,btn8h);
        listaBotones.add(8,btn7a);
        listaBotones.add(9,btn7b);
        listaBotones.add(10,btn7c);
        listaBotones.add(11,btn7d);
        listaBotones.add(12,btn7e);
        listaBotones.add(13,btn7f);
        listaBotones.add(14,btn7g);
        listaBotones.add(15,btn7h);
        listaBotones.add(16,btn6a);
        listaBotones.add(17,btn6b);
        listaBotones.add(18,btn6c);
        listaBotones.add(19,btn6d);
        listaBotones.add(20,btn6e);
        listaBotones.add(21,btn6f);
        listaBotones.add(22,btn6g);
        listaBotones.add(23,btn6h);
        listaBotones.add(24,btn5a);
        listaBotones.add(25,btn5b);
        listaBotones.add(26,btn5c);
        listaBotones.add(27,btn5d);
        listaBotones.add(28,btn5e);
        listaBotones.add(29,btn5f);
        listaBotones.add(30,btn5g);
        listaBotones.add(31,btn5h);
        listaBotones.add(32,btn4a);
        listaBotones.add(33,btn4b);
        listaBotones.add(34,btn4c);
        listaBotones.add(35,btn4d);
        listaBotones.add(36,btn4e);
        listaBotones.add(37,btn4f);
        listaBotones.add(38,btn4g);
        listaBotones.add(39,btn4h);
        listaBotones.add(40,btn3a);
        listaBotones.add(41,btn3b);
        listaBotones.add(42,btn3c);
        listaBotones.add(43,btn3d);
        listaBotones.add(44,btn3e);
        listaBotones.add(45,btn3f);
        listaBotones.add(46,btn3g);
        listaBotones.add(47,btn3h);
        listaBotones.add(48,btn2a);
        listaBotones.add(49,btn2b);
        listaBotones.add(50,btn2c);
        listaBotones.add(51,btn2d);
        listaBotones.add(52,btn2e);
        listaBotones.add(53,btn2f);
        listaBotones.add(54,btn2g);
        listaBotones.add(55,btn2h);
        listaBotones.add(56,btn1a);
        listaBotones.add(57,btn1b);
        listaBotones.add(58,btn1c);
        listaBotones.add(59,btn1d);
        listaBotones.add(60,btn1e);
        listaBotones.add(61,btn1f);
        listaBotones.add(62,btn1g);
        listaBotones.add(63,btn1h);
    }
    
    public void desopacarBotones(){
        for(JButton btn: listaBotones){
            btn.setContentAreaFilled(false);
            
        }
    }
    
    private void desactivarBotones(){
        java.awt.Color amarilloNuestro = java.awt.Color.getHSBColor(114, 76, 100);
        for(JButton btn: listaBotones){
            btn.setEnabled(false);
            btn.setBackground(amarilloNuestro);
        }
    }
    
    public void pintarTablero() throws IllegalTableroException{
        ArrayList<ModeloUsuario> aux = user.getModelosUsuario();
        Modelo modelo = aux.get(aux.size()-1).getModelo();
        T = modelo.getTablero();
        T.tableroIlegal();
        int seleccionboton;
        for (int i=1; i<9; i++){ //con el array de botones, le vamos a asignar a cada uno un icono dependiendo de su figura src/interfaz_grafica/jugada.txt
            //System.out.println("prueba");
            for(int j=0; j<8; j++){
                char jc = (char) j;
                jc += 97; //para añadirlo en tipo posicion que luego lo que hace es restar 97
                int y= 9-i;
                Posicion pos = new Posicion(y,(char)jc);
                System.out.println(pos.toString());
                System.out.println("i" + i);
                System.out.println("j "+ j);
                System.out.println("prueba");
                ImageIcon icon;
                if(T.GetPiezaPos(pos)!=null){
                    //leemos qué figura es
                    Pieza p = T.GetPiezaPos(pos);
                    seleccionboton= (i-1)*8 + j;
                    listaBotones.get(seleccionboton).setEnabled(true);/*Habilitamos el botón
                    cuya posición asociada esté ocupada por una pieza*/
                    
                    //haremos un switch para saber qué foto meter en el icon
                    switch (p.getNombre()){
                        case 'R': 
                            switch(p.getColor().toString()){
                                case "N": {
                                    icon = new ImageIcon(getClass().getResource("bk.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                } 
                                case "B":{
                                    icon = new ImageIcon(getClass().getResource("wk.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                            }
                            System.out.println("cargamos rey");
                            break;
                        case 'T': 
                            switch(p.getColor().toString()){
                                case "N": {
                                    icon = new ImageIcon(getClass().getResource("br.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                                case "B":{
                                    icon = new ImageIcon(getClass().getResource("wr.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                            }
                            break;
                        case 'A': 
                            switch(p.getColor().toString()){
                                case "N":  {
                                    icon = new ImageIcon(getClass().getResource("bb.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                                case "B":{
                                    icon = new ImageIcon(getClass().getResource("wb.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                            }
                            break;
                        case 'C': 
                            switch(p.getColor().toString()){
                                case "N":{
                                    icon = new ImageIcon(getClass().getResource("bn.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                                case "B":{
                                    icon = new ImageIcon(getClass().getResource("wn.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                            }
                            break;
                        case 'P': 
                            switch(p.getColor().toString()){
                                case "N": {
                                    icon = new ImageIcon(getClass().getResource("bp.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                                case "B":{
                                    icon = new ImageIcon(getClass().getResource("wp.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                            }
                            break;
                        case 'D': 
                            switch(p.getColor().toString()){
                                case "N": {
                                    icon = new ImageIcon(getClass().getResource("bq.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                                case "B": {
                                    icon = new ImageIcon(getClass().getResource("wq.png"));
                                    listaBotones.get(seleccionboton).setIcon(icon);
                                    break;
                                }
                            }
                            break;
                    }//end switch de getNombre de pieza
                }//end comprobación pieza no nula
            }//end for variable j
        }//end for variable i


    }
    
    private void jButtonResolverProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResolverProblemaActionPerformed
        try{
        this.pintarTablero();
       }
       catch(IllegalTableroException e1){ 
       }
       deshabilitarUI();
       
    }//GEN-LAST:event_jButtonResolverProblemaActionPerformed
    private void jButtonEstadisticasPersonalesActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        ArrayList<Usuario> auser = sys.getUsuarios();
        Usuario user = auser.get(auser.size()-1); //siempre sera el ultimo que se ha logeado
        double pr = user.porcentajeExito();
        int in = user.getNProblemasInt();
        int in1 = user.getNProblemasSol();
        int in2 = user.getNErrores();
        String nombre1 = user.getNombre();
        JOptionPane.showMessageDialog(this,"           Clasificación personal de " + nombre1+"\n"+"Porcentaje de éxito: "+pr+" \n"+ "Problemas intentados: " + in + " \n" + "Problemas solucionados: " + in1 + " \n" + "Errores: " + in2,"Clasificación personal",JOptionPane.PLAIN_MESSAGE,null );
        







// TODO add your handling code here:
    }  
    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        
            int respuesta;
            Object[] options = { "Guardar", "Leer" };
                respuesta = JOptionPane.showOptionDialog(
                        this, //Ventana padre
                        "Escoge si quieres guardar los datos o leer los datos ",//Mensaje del cuerpo
                        "Atención",//Texto de encabezado
                        JOptionPane.YES_NO_OPTION, //Tipo de opciones a mostrar
                        JOptionPane.QUESTION_MESSAGE, //Tipo del mensaje a mostrar
                        null,//Icono a mostrar
                        options,//array con las elecciones posibles
                        options[0]);
                if(respuesta==0){
                    int returnVal = selectorArchivos.showOpenDialog(this);/*Mostrar el explorador
                        de archivos*/
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            /*Obtener el archivo seleccionado*/
            File archivo = selectorArchivos.getSelectedFile();
            String codigoError = "";
            try {
                /*Obtener la ruta del archivo seleccionado*/
                jLabelInformacion.setText(archivo.getCanonicalPath());
                sys.EscribirBinarioUsuarios(jLabelInformacion.getText());
                
            } catch (FileNotFoundException ex) {
                codigoError = "Archivo no encontrado.";
            } catch (Exception ex) {
                codigoError = ex.getMessage();
                
            } }}
                
                
              if(respuesta==1){
                    int returnVal = selectorArchivos.showOpenDialog(this);/*Mostrar el explorador
                        de archivos*/
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            /*Obtener el archivo seleccionado*/
            File archivo = selectorArchivos.getSelectedFile();
            String codigoError = "";
            try {
                /*Obtener la ruta del archivo seleccionado*/
                jLabelInformacion.setText(archivo.getCanonicalPath());
                sys.LeerBinarioUsuarios(jLabelInformacion.getText());
                
            } catch (FileNotFoundException ex) {
                codigoError = "Archivo no encontrado.";
            } catch (Exception ex) {
                codigoError = ex.getMessage();
                
            } }}
                
                 
            



sys.actualizarSistemaModelos();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed
private void jButtonEstadisticasProblemasActionPerformed(java.awt.event.ActionEvent evt) {                                                             
       int nUsuarios = 0;
       int intentos=0;
       int fallos =0;
       int indice1;
       int indice2 = 0;
       jLabelInformacion.setText("");
        for(Modelo m : sys.getModelos() ){
            for (Usuario u: sys.getUsuarios()){
                if(u.getModelosResueltos().contains(m)){
                   indice1 = u.getModelosUsuario().indexOf(m);
                   intentos += u.getModelosUsuario().get(indice1).getIntentos();
                   fallos += u.getModelosUsuario().get(indice1).getErrores();
                   nUsuarios +=1;
                }
              indice2 +=1;
              if (nUsuarios>0){
              jLabelInformacion.setText(jLabelInformacion.getText()+" .El problema nº " + indice2 + " tiene  una media de errores de "+fallos/nUsuarios+"(con un total de " +fallos+" fallos) ,una media de intentos de "+ intentos/nUsuarios + "(con un total de "+intentos+" intentos).\n " ) ;
              }else{jLabelInformacion.setText(jLabelInformacion.getText()+" .El problema nº " + indice2 +" No se ha intentado todavia");}
              intentos = 0;
              fallos = 0;
              nUsuarios = 0;
            }
        }
        
    }

    
    private Posicion getPosicionBoton(JButton b){
        int coordX = Character.getNumericValue(b.getName().charAt(3));
        char coordY = b.getName().charAt(4);
        return new Posicion(coordX, coordY);
    }
    
    /**
     * @param args the command line arguments
     */
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1a;
    private javax.swing.JButton btn1b;
    private javax.swing.JButton btn1c;
    private javax.swing.JButton btn1d;
    private javax.swing.JButton btn1e;
    private javax.swing.JButton btn1f;
    private javax.swing.JButton btn1g;
    private javax.swing.JButton btn1h;
    private javax.swing.JButton btn2a;
    private javax.swing.JButton btn2b;
    private javax.swing.JButton btn2c;
    private javax.swing.JButton btn2d;
    private javax.swing.JButton btn2e;
    private javax.swing.JButton btn2f;
    private javax.swing.JButton btn2g;
    private javax.swing.JButton btn2h;
    private javax.swing.JButton btn3a;
    private javax.swing.JButton btn3b;
    private javax.swing.JButton btn3c;
    private javax.swing.JButton btn3d;
    private javax.swing.JButton btn3e;
    private javax.swing.JButton btn3f;
    private javax.swing.JButton btn3g;
    private javax.swing.JButton btn3h;
    private javax.swing.JButton btn4a;
    private javax.swing.JButton btn4b;
    private javax.swing.JButton btn4c;
    private javax.swing.JButton btn4d;
    private javax.swing.JButton btn4e;
    private javax.swing.JButton btn4f;
    private javax.swing.JButton btn4g;
    private javax.swing.JButton btn4h;
    private javax.swing.JButton btn5a;
    private javax.swing.JButton btn5b;
    private javax.swing.JButton btn5c;
    private javax.swing.JButton btn5d;
    private javax.swing.JButton btn5e;
    private javax.swing.JButton btn5f;
    private javax.swing.JButton btn5g;
    private javax.swing.JButton btn5h;
    private javax.swing.JButton btn6a;
    private javax.swing.JButton btn6b;
    private javax.swing.JButton btn6c;
    private javax.swing.JButton btn6d;
    private javax.swing.JButton btn6e;
    private javax.swing.JButton btn6f;
    private javax.swing.JButton btn6g;
    private javax.swing.JButton btn6h;
    private javax.swing.JButton btn7a;
    private javax.swing.JButton btn7b;
    private javax.swing.JButton btn7c;
    private javax.swing.JButton btn7d;
    private javax.swing.JButton btn7e;
    private javax.swing.JButton btn7f;
    private javax.swing.JButton btn7g;
    private javax.swing.JButton btn7h;
    private javax.swing.JButton btn8a;
    private javax.swing.JButton btn8b;
    private javax.swing.JButton btn8c;
    private javax.swing.JButton btn8d;
    private javax.swing.JButton btn8e;
    private javax.swing.JButton btn8f;
    private javax.swing.JButton btn8g;
    private javax.swing.JButton btn8h;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButtonEstadisticasPersonales;
    private javax.swing.JButton jButtonEstadisticasProblemas;
    private javax.swing.JButton jButtonNombrePassword;
    private javax.swing.JButton jButtonResolverProblema;
    private javax.swing.JButton jButtonSubirProblema;
    private javax.swing.JButton jButtonVerClasificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInformacion;
    private javax.swing.JLabel jLabelInsertarNombre;
    private javax.swing.JLabel jLabelInsertarPass;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JPasswordField jTextPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        System.out.println("Me pulsó");; //To change body of generated methods, choose Tools | Templates.
    }
}
