/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p_final.interfaz_grafica;
import p_final.*;
import java.util.*;
import javax.swing.*;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.util.ArrayList;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Juan
 */
public class jframeprincipal extends javax.swing.JFrame {

    /**
     * Creates new form jframeprincipal
     */
    public jframeprincipal() {
        initComponents();
        deshabilitarUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextPassword = new javax.swing.JPasswordField();
        jLabelInsertarNombre = new javax.swing.JLabel();
        jLabelInsertarPass = new javax.swing.JLabel();
        jLabelInformacion = new javax.swing.JLabel();
        jButtonNombrePassword = new javax.swing.JButton();
        jButtonSubirProblema = new javax.swing.JButton();
        jButtonResolverProblema = new javax.swing.JButton();
        jButtonEstadisticasPersonales = new javax.swing.JButton();
        jButtonEstadisticasProblemas = new javax.swing.JButton();
        jButtonVerClasificacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, 60));

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 80, 70));

        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 70, 60));

        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 70, 60));

        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 70, 60));

        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 70, 60));

        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 70, 60));

        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 70, 60));

        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 70, 70));

        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 70, 70));

        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 70, 70));

        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 70, 70));

        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 70, 70));

        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 70, 70));

        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 70, 70));

        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 70, 70));

        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 70, 70));

        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 70, 70));

        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 70, 70));

        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 70, 70));

        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 70, 70));

        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 70, 70));

        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 70, 70));

        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 70, 70));

        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, 70));

        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 70, 70));

        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 70, 70));

        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 70, 70));

        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 70, 70));

        jButton30.setBorderPainted(false);
        jButton30.setContentAreaFilled(false);
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 70, 70));

        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 70, 70));

        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 70, 70));

        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 70, 70));

        jButton34.setBorderPainted(false);
        jButton34.setContentAreaFilled(false);
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 70, 70));

        jButton35.setBorderPainted(false);
        jButton35.setContentAreaFilled(false);
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 70, 70));

        jButton36.setBorderPainted(false);
        jButton36.setContentAreaFilled(false);
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 70, 70));

        jButton37.setBorderPainted(false);
        jButton37.setContentAreaFilled(false);
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 70, 70));

        jButton38.setBorderPainted(false);
        jButton38.setContentAreaFilled(false);
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 70, 70));

        jButton39.setBorderPainted(false);
        jButton39.setContentAreaFilled(false);
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 70, 70));

        jButton44.setBorderPainted(false);
        jButton44.setContentAreaFilled(false);
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 70, 70));

        jButton46.setBorderPainted(false);
        jButton46.setContentAreaFilled(false);
        getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 70, 70));

        jButton47.setBorderPainted(false);
        jButton47.setContentAreaFilled(false);
        getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 70, 70));

        jButton48.setBorderPainted(false);
        jButton48.setContentAreaFilled(false);
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 70, 70));

        jButton66.setBorderPainted(false);
        jButton66.setContentAreaFilled(false);
        getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 70, 70));

        jButton67.setBorderPainted(false);
        jButton67.setContentAreaFilled(false);
        getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 70, 70));

        jButton68.setBorderPainted(false);
        jButton68.setContentAreaFilled(false);
        getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 70, 70));

        jButton69.setBorderPainted(false);
        jButton69.setContentAreaFilled(false);
        getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 70, 70));

        jButton70.setBorderPainted(false);
        jButton70.setContentAreaFilled(false);
        getContentPane().add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 70, 70));

        jButton71.setBorderPainted(false);
        jButton71.setContentAreaFilled(false);
        getContentPane().add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 70, 70));

        jButton72.setBorderPainted(false);
        jButton72.setContentAreaFilled(false);
        getContentPane().add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 70, 70));

        jButton73.setBorderPainted(false);
        jButton73.setContentAreaFilled(false);
        getContentPane().add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 70, 70));

        jButton74.setBorderPainted(false);
        jButton74.setContentAreaFilled(false);
        getContentPane().add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 70, 70));

        jButton75.setBorderPainted(false);
        jButton75.setContentAreaFilled(false);
        getContentPane().add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 70, 70));

        jButton76.setBorderPainted(false);
        jButton76.setContentAreaFilled(false);
        getContentPane().add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 70, 70));

        jButton77.setBorderPainted(false);
        jButton77.setContentAreaFilled(false);
        getContentPane().add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 70, 70));

        jButton78.setBorderPainted(false);
        jButton78.setContentAreaFilled(false);
        getContentPane().add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 70, 70));

        jButton79.setBorderPainted(false);
        jButton79.setContentAreaFilled(false);
        getContentPane().add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 70, 70));

        jButton80.setBorderPainted(false);
        jButton80.setContentAreaFilled(false);
        getContentPane().add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 70, 70));

        jButton81.setBorderPainted(false);
        jButton81.setContentAreaFilled(false);
        getContentPane().add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 70, 70));

        jButton82.setBorderPainted(false);
        jButton82.setContentAreaFilled(false);
        getContentPane().add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 70, 70));

        jButton83.setBorderPainted(false);
        jButton83.setContentAreaFilled(false);
        getContentPane().add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 70, 70));

        jButton84.setBorderPainted(false);
        jButton84.setContentAreaFilled(false);
        getContentPane().add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 70, 70));

        jButton85.setBorderPainted(false);
        jButton85.setContentAreaFilled(false);
        getContentPane().add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 70, 70));

        jButton86.setBorderPainted(false);
        jButton86.setContentAreaFilled(false);
        getContentPane().add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 70, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p_final/interfaz_grafica/tablero_final.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jTextNombre.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 110, -1));

        jTextPassword.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        getContentPane().add(jTextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 120, -1));

        jLabelInsertarNombre.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabelInsertarNombre.setText("Inserta tu nombre");
        getContentPane().add(jLabelInsertarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jLabelInsertarPass.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabelInsertarPass.setText("Inserta tu contraseña");
        getContentPane().add(jLabelInsertarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jLabelInformacion.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        getContentPane().add(jLabelInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 280, 310));

        jButtonNombrePassword.setText("OK");
        jButtonNombrePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNombrePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNombrePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, -1, -1));

        jButtonSubirProblema.setText("Subir problema");
        jButtonSubirProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubirProblemaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSubirProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 260, 20));

        jButtonResolverProblema.setText("Resolver problema");
        jButtonResolverProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResolverProblemaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResolverProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 35, 260, 20));

        jButtonEstadisticasPersonales.setText("Estadísticas personales");
        getContentPane().add(jButtonEstadisticasPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 260, 20));

        jButtonEstadisticasProblemas.setText("Estadísticas de los problemas");
        getContentPane().add(jButtonEstadisticasProblemas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 260, 20));

        jButtonVerClasificacion.setText("Ver clasificación");
        getContentPane().add(jButtonVerClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 260, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Sistema sys = new Sistema();
    String nombre, pass;
    Usuario user;
    ArrayList<ModeloUsuario> AUSER;
   
    final JFileChooser selectorArchivos = new JFileChooser(); //Creamos un selector de archivos
    private void habilitarUI(){
        jButtonNombrePassword.setVisible(false);//Esconder botón "OK"
        jTextNombre.setVisible(false);//Esconder cuadro de texto para leer nombre
        jTextPassword.setVisible(false);//Esconder cuadro de texto para leer password
        jLabelInsertarNombre.setVisible(false);//Esconder etiqueta de insertar nombre
        jLabelInsertarPass.setVisible(false);//Esconder etiqueta de insertar password
        jLabelInformacion.setText("Bienvenido, "+ nombre + ", disfruta de esta partida.");/*Sacar
        mensaje por nuestra terminal de información*/
        jButtonSubirProblema.setVisible(true);/*Posibilitamos subir problema ahora
        que tenemos un usuario que ha hecho log-in*/
        jButtonResolverProblema.setVisible(true);
        jButtonEstadisticasPersonales.setVisible(true);
        jButtonVerClasificacion.setVisible(true);
        jButtonEstadisticasProblemas.setVisible(true);
    }
    
    private void deshabilitarUI(){
        jButtonSubirProblema.setVisible(false);/*Posibilitamos subir problema ahora
        que tenemos un usuario que ha hecho log-in*/
        jButtonResolverProblema.setVisible(false);
        jButtonEstadisticasPersonales.setVisible(false);
        jButtonVerClasificacion.setVisible(false);
        jButtonEstadisticasProblemas.setVisible(false);
    }
    
    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    
    
    private void jButtonNombrePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNombrePasswordActionPerformed
        nombre = jTextNombre.getText();
        pass = jTextPassword.getText();
        int respuesta = 0;
        if(!nombre.equalsIgnoreCase("") && !pass.equalsIgnoreCase("")){
            if(sys.buscarUsuario(nombre, pass) == null){
                Object[] options = { "Sí", "No" };
                respuesta = JOptionPane.showOptionDialog(
                        this, //Ventana padre
                        "Usuario no encontrado. ¿Desea registrarse al sistema?",//Mensaje del cuerpo
                        "Atención",//Texto de encabezado
                        JOptionPane.YES_NO_OPTION, //Tipo de opciones a mostrar
                        JOptionPane.QUESTION_MESSAGE, //Tipo del mensaje a mostrar
                        null,//Icono a mostrar
                        options,//array con las elecciones posibles
                        options[0]);
            }else{
                habilitarUI();
            }
            if(respuesta==0){
                sys.registrarUsuario(nombre, nombre);
                habilitarUI();
            }
        }
    }//GEN-LAST:event_jButtonNombrePasswordActionPerformed

    private void jButtonSubirProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubirProblemaActionPerformed
        int returnVal = selectorArchivos.showOpenDialog(this);/*Mostrar el explorador
        de archivos*/
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            /*Obtener el archivo seleccionado*/
            File archivo = selectorArchivos.getSelectedFile();
            /*Obtener la ruta del archivo seleccionado*/
            jLabelInformacion.setText(archivo.getAbsolutePath());
            
        }
    }//GEN-LAST:event_jButtonSubirProblemaActionPerformed

    private void jButtonResolverProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResolverProblemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonResolverProblemaActionPerformed

    /**
     * @param args the command line arguments
     */
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframeprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonEstadisticasPersonales;
    private javax.swing.JButton jButtonEstadisticasProblemas;
    private javax.swing.JButton jButtonNombrePassword;
    private javax.swing.JButton jButtonResolverProblema;
    private javax.swing.JButton jButtonSubirProblema;
    private javax.swing.JButton jButtonVerClasificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInformacion;
    private javax.swing.JLabel jLabelInsertarNombre;
    private javax.swing.JLabel jLabelInsertarPass;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JPasswordField jTextPassword;
    // End of variables declaration//GEN-END:variables
}
